# Generated by Django 5.0.1 on 2024-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logged_in_num',
            field=models.IntegerField(default=5),
        ),
    ]
