# Generated by Django 5.0.1 on 2024-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpro', '0002_alter_userprofile_logged_in_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='logged_in_num',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='n_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
