# Generated by Django 5.0.1 on 2024-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpro', '0003_remove_userprofile_logged_in_num_userprofile_n_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='n_value',
            field=models.IntegerField(default=5),
        ),
    ]
